name: yandex_geocoder
description: API to translate geographic coordinates into an address and vice versa
version: 2.2.0
repository: https://github.com/MadBrains/Yandex-Geocoder-Flutter
issue_tracker: https://github.com/MadBrains/Yandex-Geocoder-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  http: ^1.0.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  